services:
  mad-signals:
    build:
      context: .
    image: mad-signals:latest
    container_name: mad-signals
    restart: on-failure
    environment:
      TZ: ${TZ:-Europe/Amsterdam}
      M_AD_OUTPUT_DIR: /data
    volumes:
      - ${M_AD_DATA_DIR:-./data}:/data
    stdin_open: true
    tty: true
